### ISSUE TITLE
Single event page design

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#14]
Related events could be by location and/or by something related to the content (could be tags or just similar titles).
Indicating a number for games (this can be a useful info).

![event page mockup](https://user-images.githubusercontent.com/969003/72685021-312ad080-3ae6-11ea-93b2-0e2afafb973a.png)

**Comment by engleek** [comment]
Might need that cool location input from Algolia!

**Comment by engleek** [comment]
I would say that this page is at least ready for feedback & testing. Further improvements and bugs can be addressed with new issues.
