### ISSUE TITLE
Studios / associations don't have logos

### ISSUE THREAD

**Issue by engleek** [indie-collective/community#17]
Organisations don't currently allow uploading of logos. In fact, I'm not sure organisations have logos…

**Comment by engleek** [comment]
Looks like we're not using logos after all, so maybe we need to think about a design without images?

**Comment by YoruNoHikage** [comment]
I just haven't added upload for them yet 😭

**Comment by engleek** [comment]
Maybe we should select some default logos in the meantime.
Something from here https://game-icons.net ?

**Comment by YoruNoHikage** [comment]
I think it's easier to add the upload than having default random icons. But I like these icons, we could use them for something else (default avatars?)
