### ISSUE TITLE
Add event status

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#20]
With the different cancellations happening now, it could be nice to have some kind of status for the events. I first think of **ongoing** and **canceled** but there may be more. This issue is opened as a way to discuss it and as a reminder for some nice ideas around it.

Meetup
- Crossing out date and time
  ![image](https://user-images.githubusercontent.com/969003/76785149-2e322080-67b5-11ea-9ff5-a223165d635f.png)
- Big headband
  ![image](https://user-images.githubusercontent.com/969003/76785167-38ecb580-67b5-11ea-807c-1510d9758858.png)

Facebook
![image](https://user-images.githubusercontent.com/969003/76786756-0b553b80-67b8-11ea-985f-e812636735c7.png)

**Comment by engleek** [comment]
Maybe we could add a label to cards to indicate cancelled status? Like in this page https://semantic-ui.com/elements/label.html

**Comment by engleek** [comment]
Can we say that this is closed?

**Comment by YoruNoHikage** [comment]
Not done yet

**Comment by YoruNoHikage** [comment]
Let me reopen this one. I think it can be done in the coming days/weeks.
I'm not a huge fan of the label, not easy to notice I'd say, not that I'm right but the crossed title or the headband is better visually.
