### ISSUE TITLE
Game image upload

### ISSUE THREAD

**Issue by engleek** [indie-collective/community#24]
Hey @YoruNoHikage , how far did you get with this?

https://github.com/indie-collective/community/blob/6c9082c1e9631ffb418a47b27248f530155b8309/client/pages/games/create.jsx#L69

What's the next step?

**Comment by engleek** [comment]
Where would you put the dropzone?

The many to many on game <-> image seems easy enough. Want me to handle it?

**Comment by YoruNoHikage** [comment]
Actually, the many to many was already there. Dropzone incoming.
