### ISSUE TITLE
Homepage visitor design

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#25]
Just throwing some ideas for the homepage. I was thinking of it as a page presenting some generic data, maybe some graphs that could serve as entry points for other pages. Anything that could trigger interest for a gamedev living in Canada, a gamer in Australia, a journalist in France... Should we add recently added data as well?

![image](https://user-images.githubusercontent.com/969003/85201661-84a58280-b301-11ea-8bbd-3406da070e51.png)

Link for enhancement: https://excalidraw.com/#json=5737844588937216,smPNF9VUAr8LfpJQ3uGMdA

Anything that comes in mind?

**Comment by engleek** [comment]
The map is a cool idea. Maybe we can even locate it for the visitor.

I think it's a really good first version. The next one would have to come from what Hotjar and feedback can reveal to us.

**Comment by engleek** [comment]
If we had types attached to the games/orgs/events we could display some kind of stylized statistic about what kind of things are present. Like "lots of strategy games!".

Also we have several association type orgs which kind of get lost in the studios, and lots of studios with no games.

**Comment by engleek** [comment]
As it is, I think the home page isn't bad. Though it might need better laid out sections with copy (text) so the page has a flow of conversation.

I also think that the page could do with breathing. Maybe reducing the max page width to 800 and the number of games on a page so visitors aren't overloaded with content.

I'm also afraid that "orgs" is a bit vague. It might be an idea to have studios / associations and set aside organisations for now.
