### ISSUE TITLE
Tag system

### ISSUE THREAD

**Issue by mrasska** [indie-collective/community#27]
For a better UX, there is a need to have a **search/tag system**. This system can be applied to the "Games" and "Orgs" part of the website. 

### Suggestion for the "Games" section:
- Genre : FPS / Platformer / Puzzle 
- Date of release : 
- Studios : 
- Nationality of the studio : Country 
- Platform : Steam / Itchio / Epic Games Store / GoG / Humble Store
- Multi-player : No / Online / Local 

### Suggestion for the "Orgs" section:
- Type : Studio / None Lucrative Org
- Nationality : Country 
- Localisation : City 

Type of display : drop-down menu (?)

**Comment by drunkmoriarty** [comment]
Idea for Games & Orgs pages design : https://excalidraw.com/#json=5736030116249600,Xm5jU4JxULyhaJxCrJC2sQ

**Comment by engleek** [comment]
Hey, my two cents.

## Games

Some of these tags I think are easier to do than others: genre, platform, multi
Others I think might be quite hard: Release date for ex (what is a release? are releases finished games? will people take the time to release? is a jam project released?)
Others are more than tags they're actual associations : Studio, Studio Location

## Studios 

Those tags are also associations.

Nationality : Country
Localisation : City

And maybe we should add **Associations** for non lucrative entities?

**Comment by drunkmoriarty** [comment]
Hey, _my 50 cents_ ! 

## Games 
True for the 'release date' tag. 
I don't think that 'Studio Location' would be a relevant for the search system. Need to be tested.

**Comment by engleek** [comment]
We have $1.

For search it might be cool to look for studios near a place. I really would love to work on some lorez maps with events/studios and be able to explore those a bit.

For tags though I'm not sure. I mean it's all discovery and searching anyway…

I'm thinking we can implement a base tagging system with limited options and then have a simple UI up and running without too much effort. However the queries scare me a bit, what say you @YoruNoHikage ?

**Comment by engleek** [comment]
Oups, things don't work the way I thought.

We have this tag table.

```sql
create table indieco.tag (
  id               uuid primary key default uuid_generate_v4(),
  name             varchar (30) not null check (char_length(name) < 30),
  created_at       timestamptz default now()
);
```

In the game table tags use a string list though.

```sql
create table indieco.game (
  id               uuid primary key default uuid_generate_v4(),
  name             text not null check (char_length(name) < 80),
  about            text,
  site             text check (char_length(name) < 512),
  tag_list          varchar (30) [],
  created_at       timestamptz default now()
);
```

Maybe we can keep it this way but use the tag table to store allowed tags and colour/type?

**Comment by drunkmoriarty** [comment]
> For search it might be cool to look for studios near a place. I really would love to work on some lorez maps with events/studios and be able to explore those a bit.

I understand the logic behind it. However, how are we gonna deal -if there will be some- about studio that operate remotely?
We will need to have a solution about it for the long term. 

@engleek Can you translate the meaning of your tables please ? I don't know what kind of language it is ^^ .

**Comment by engleek** [comment]
@drunkmoriarty It's SQL. Or rather it's SQL for PostgreSQL. pgSQL I think. It's not the query language but the schema language. It's not super complicated. You have descriptions for tables and the columns in each table. Each column has a label then it's type/constraints.

As for locations, I'm not sure there is a solution. People and companies move around. Some are distributed and remote. I'm sure someone will tell us the day we're not descriptive enough 😄

**Comment by engleek** [comment]
Alexis did a good job (though he disagrees) of putting the finishing touches on version 1 of tags 👍
