### ISSUE TITLE
Motivations

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#28]
Here's what we want / need to do for the project.

Being able to see what is going on around you when it comes to game making. (through city pages and events)

**Comment by engleek** [comment]
I want to be able to explore and have an overview of games, creators and groups around the world.

**Comment by drunkmoriarty** [comment]
I want to have a clean and user-friendly platform where I can find infos about the indie world : games, creators, events.

**Comment by engleek** [comment]
# About the Indie Collective Community

We wanted a friendly and open place to keep in touch with studios, explore indie games and follow events.

**Comment by drunkmoriarty** [comment]
Creating a tab to talk about Indie Collective and its projects is a good thing to add to the website. 

Should we put the elements we want to add to the website into the planning ? Or create a new projects in which we put elements into box depending on its position in the time scale ?

**Comment by engleek** [comment]
@Aeden-B @feoche Guys, we don't have your opinions. You don't have to have one of course, but maybe!

**Comment by feoche** [comment]
> @Aeden-B @feoche Guys, we don't have your opinions. You don't have to have one of course, but maybe!

List past/future indie projects & its gravitating environment, while presenting jams & its resulting games
