### ISSUE TITLE
Present projects and the association motivations on the web site

### ISSUE THREAD

**Issue by engleek** [indie-collective/community#30]
Creating a tab to talk about Indie Collective and its projects is a good thing to add to the website. 

Should we put the elements we want to add to the website into the planning ? Or create a new projects in which we put elements into box depending on its position in the time scale ?

_Originally posted by @drunkmoriarty in https://github.com/indie-collective/community/issues/28#issuecomment-716131871_

**Comment by YoruNoHikage** [comment]
It could be a link to Indie Collective's organization page within the community.

**Comment by mrasska** [comment]
> 
> 
> It could be a link to Indie Collective's organization page within the community.

The best position for this would on the top section, next to the event section. What do you think ?

**Comment by YoruNoHikage** [comment]
Do we really need to emphasize it that much? It could just be a simple link in the footer, even though we don't have one yet.

**Comment by mrasska** [comment]
> 
> 
> Do we really need to emphasize it that much? It could just be a simple link in the footer, even though we don't have one yet.

I believe it would be great to put it in the top side.
