### ISSUE TITLE
Global search bar

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#31]
Hello again! We need to talk.

**Search is the next big thing for Community. Here some questions to make things a bit clearer:**

What does the search bar do and where does it take us?
Which tech should we use to get a nice experience ignoring typos, being cross-languages... ?

Ultimately, we need to figure out what will the visitor think will do when typing into this search bar.

*Here's my take on this, waiting for yours:*

**What does the search bar do and where does it take us?**
When typing words, you get different suggestions within games, orgs, events, tags.
If you choose not to follow one of the suggestion, you get a full page (/search) with several results (like the home page but with specific data related to what you typed.
If you do choose to follow one of the suggestion, either you get to:
- the page (game, org, event)
- the filtered games page (tag)

I have no idea for the tech @engleek has to know or we're screwed (= I don't want to pick one).

**Comment by engleek** [comment]
Aaaaaaaah! Choosing technology! Both my favorite and least favorite thing to do.

**Objective**
Looks good to me!
I would say first the component in itself, then the full page if we can't ever find what we're looking for.
Keyboard interaction FTW!

**Tech**
We're probably going with a GraphQL endpoint, so we'll need to work with union types.
Without jumping on a search engine (I would choose http://meilisearch.com), we can already write some cool SQL with %like% clauses and test out the search functions. From what I gather that would mean writing one for each table and then calling three GraphQL functions, but maybe that's cool too?

**Comment by YoruNoHikage** [comment]
The first version is available. It is a very limited way of searching, only through names and it can't handle typos. I'd like to investigate more in a search engine like meilisearch but not sure where to sync data with PgSQL.
