### ISSUE TITLE
Move away from Algolia Places

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#32]
Algolia Places we use as an autocomplete input to get addresses for events (for now) is going down within 18 months. We need to pick an alternative to it.

Google Places is great but out of question for monetary and proprietary reasons.
Mapbox is proprietary but sounds ok and is a collection of OpenStreetMap data / official datasets.

Or we could go full open street map with one of those services: https://wiki.openstreetmap.org/wiki/Search_engines#Search_engine_services

I think for any of those it should be easy to find an already built autocomplete input.

**Comment by engleek** [comment]
I like the Mapbox service, and I'm sure we can stay under the use limits.

Your idea of collecting places progressively and focusing on those instead of just addresses seems really cool.

**Comment by YoruNoHikage** [comment]
Moved to Mapbox!
