### ISSUE TITLE
Image caching : setting up a CDN

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#33]
**Is your feature request related to a problem? Please describe.**
Images are not cached and takes time to load, sometimes they don't even load properly.

**Describe the solution you'd like**
Setting up a simple CDN in front of the S3 bucket we have (the way we do now is not recommended).
Could setting up a simple CloudFlare in front of the current URL be working as a solution ?

**Describe alternatives you've considered**
There's no alternative that I could think of besides saving a low-res preview in db to get a quick preview. But that's more of way to get around the problem.

**Comment by engleek** [comment]
I have no experience in CDN tech. I know that Varnish and Redis at a pinch can do the job.

As for services… looks like there are a lot, but Cloudflare is cool. There's a basic free tier isn't there?

**Comment by YoruNoHikage** [comment]
Yes there is, I've tried setting something up, looks like it works.
