### ISSUE TITLE
Sort & select images through a thumbs up/down system

### ISSUE THREAD

**Issue by YoruNoHikage** [indie-collective/community#4]
To select the image we should display on a community-managed page, every user should be able to up/down vote an image. The ratio could then be used to sort the different images, the one with the highest might be displayed on other pages.

**Comment by engleek** [comment]
How do we sort images when there aren't any scores? Last one uploaded?

**Comment by YoruNoHikage** [comment]
😭

**Comment by YoruNoHikage** [comment]
I'm still thinking about implementing this. And yup, score and last one uploaded.

**Comment by engleek** [comment]
Still thinking? :D

**Comment by YoruNoHikage** [comment]
Still thinking :D
